# Generated by Django 2.2.7 on 2019-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20191206_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='othername',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество'),
        ),
    ]
