# Generated by Django 2.2.7 on 2019-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_user_othername'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отдел'),
        ),
    ]
